dist: trusty
language: node_js
node_js:
- 9.3.0
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
cache:
  apt: true
  bundler: true
  directories:
    - node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build
script:
- karma start ./karma.conf.js --single-run
deploy:
  provider: heroku
  api_key:
    secure: Oiuri4ttOo3oHAqF0esOM4Bbu2q9wLv3Ki2kUm9zhqm50ZEXz9LSBdIrtnrl18oRw+PRr+4oHVxTXUIcjDEgI9I200nKOtlAQf1QYG6ZwA3uzYXu0fqFM/HPTyp2XO/IaEuhBHMjWtuPYN1I3HTk5LTZRc78LaU20q9PucMSOFtHjHHQrWHihhwlPvh2zcHFuX7JgThBcanHiqs3baitkjoYRqEkBfnx4wZO1ezmwoGvODMdlBm4BXVQn6uZMCekwqACKGY8OK9/4fISif1LpoQJ1CupjcSm5KSnLHk0lUP2MyFqxuOEgCfre39GhNs/9ZvgNrrZODbRNHAq/Nv17S6Rpv61333YGkLiy4xWZrsjszLeDckYPhWPooLiOhifZTOfFtuIi11POJvU3YUiQSMS67fgyDJTfW0gXrih5A7vzzIcp57xzQa5u7CKoUGsT2u49wwKIJoz6DWOjCLD9we1xLDL5qWAEYTrF7vr+QzQ3RC0w3i90EE9ukqsjL2pTvrruNAKWiJU4NT00p42vQWuUvRGB7X9kuot/S5Vraa292TE3+PgphqFINY0j0klaDVaHeRFygND6ZNs6WDLWLQcIQwcGoZy8oD0tDlKWBYPGV0ScQD77inVTm5RAJaqZ3GbOe/Q9n/spVmcERakGdz+TNr+8jixImfLTjjdfRg=
  app: 
    master: angular-sandbox
    staging: staging-angular-sandbox
  skip_cleanup: true
