version: 2
jobs:
  build:
    working_directory: ~/angular-cli-circleci
    docker:
      - image: circleci/node:7.10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run: 
          name: install
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run ng build --aot --prod
      - run:
          name: test
          command: npm run karma start ./karma.conf.js --single-run
      - run:
          name: lint
          command: npm run ng lint
