version: 2
jobs:
  build:
    working_directory: ~/angular-cli-circleci
    docker:
      - image: circleci/node:7.10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run ng build --aot --prod
      - run:
          name: Deploy
          command: |
            sudo apt-get install awscli
            aws s3 sync dist s3://angular-sandbox/ --include "*" --acl public-read --cache-control "max-age=3600" --delete
